CREATE TABLE todo_items (
    id UUID PRIMARY KEY,
    list_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    note TEXT,
    priority INTEGER NOT NULL,
    reminder TIMESTAMPTZ,
    done BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
/*    FOREIGN KEY (list_id) REFERENCES todo_lists(id)*/
);